# Generated by Django 5.0.4 on 2024-05-14 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_clientes_email_alter_pedidos_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='nombre',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.clientes'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='productos',
            field=models.ManyToManyField(to='tienda.productos'),
        ),
    ]
