# Generated by Django 5.0.6 on 2024-06-10 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_remove_pedidos_nombre_pedidos_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.clientes'),
        ),
    ]
