# Generated by Django 5.0.6 on 2024-06-15 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_registro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
