# Generated by Django 5.0.6 on 2024-06-17 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_delete_registro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='apellido',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombres',
            new_name='last_name',
        ),
    ]
